#!/bin/sh

if [ $# -ne 4 ]; then
    echo "Usage: uidmapaclshift file src dst range" 1>&2
    exit 1
fi

dir=$1
src=$2
dst=$3
range=$4

setnewacl() {
    file=$1
    newacl=""

    if [ -L "$file" ]; then
	return 0
    fi

    for a in $(getfacl -Ecnp "$file"); do
	perm=${a##*:}
	a=${a%:*}
	other=${a%:*}
	a=${a##*:}

	if [ "$a" != "" ] && [ $a -ge $src ] && [ $a -lt $(($src + $range)) ]; then
	    a=$(($a + $dst - $src))
	fi

	entry="$other:$a:$perm"

	if [ "$newacl" == "" ]; then
	    newacl="$entry"
	else
	    newacl="$newacl,$entry"
	fi
    done

    setfacl -b -m "$newacl" "$file"
}

processdir() {
    local dirpath=$1

    for file in $(ls -A "$dirpath"); do
	f="$dirpath/$file"
	if [ -L "$f" ]; then
	    continue
	elif [ -d "$f" ]; then
	    processdir "$f"
	else
	    setnewacl "$f"
	fi
    done
}

processdir "$dir"
